INSERT INTO  EMPLOYEE VALUES(1,2,'Amrit','Python');
INSERT INTO  EMPLOYEE VALUES(2,4,'Swati','Angular');
INSERT INTO  EMPLOYEE VALUES(3,2,'Parnab','Java');
INSERT INTO  EMPLOYEE VALUES(4,3,'Sam','Data Science');
